# Generated by Django 3.0.8 on 2020-07-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200713_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(default='Descategorizado', max_length=100),
        ),
    ]
