# Generated by Django 3.0.8 on 2020-07-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
