# Generated by Django 3.0.8 on 2020-07-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200715_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tamanhos',
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('tamanho', 'tamanho')], max_length=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Item')),
            ],
        ),
    ]
